# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/organization/customer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/organization/customer.proto\"\xfb\x02\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x02 \x01(\x03\x12\x13\n\x0bupdate_time\x18\x03 \x01(\x03\x12\x13\n\x0b\x64\x65lete_time\x18\x04 \x01(\x03\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x0b\n\x03sex\x18\x06 \x01(\t\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\x10\n\x08province\x18\x08 \x01(\t\x12\x0f\n\x07\x63ountry\x18\t \x01(\t\x12\x0e\n\x06\x61vatar\x18\n \x01(\t\x12\x10\n\x08nickname\x18\x0b \x01(\t\x12 \n\x06method\x18\x0c \x01(\x0e\x32\x10.Customer.Method\x12(\n\x0ewechat_profile\x18\r \x01(\x0b\x32\x0e.WechatProfileH\x00\x12(\n\x0e\x61lipay_profile\x18\x0e \x01(\x0b\x32\x0e.AlipayProfileH\x00\x12\x12\n\x08password\x18\x0f \x01(\tH\x00\" \n\x06Method\x12\n\n\x06WECHAT\x10\x00\x12\n\n\x06\x41LIPAY\x10\x01\x42\t\n\x07profile\"D\n\rWechatProfile\x12\x0e\n\x06openid\x18\x01 \x01(\t\x12\x11\n\tprivilege\x18\x02 \x01(\t\x12\x10\n\x08union_id\x18\x03 \x01(\t\" \n\rAlipayProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.organization.customer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMER._serialized_start=38
  _CUSTOMER._serialized_end=417
  _CUSTOMER_METHOD._serialized_start=374
  _CUSTOMER_METHOD._serialized_end=406
  _WECHATPROFILE._serialized_start=419
  _WECHATPROFILE._serialized_end=487
  _ALIPAYPROFILE._serialized_start=489
  _ALIPAYPROFILE._serialized_end=521
# @@protoc_insertion_point(module_scope)
