# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/openai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/api/openai.proto\"\x95\x01\n\x06Openai\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1a\n\x04type\x18\x03 \x01(\x0e\x32\x0c.Openai.Type\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\x13\n\x0b\x63reate_time\x18\x05 \x01(\x03\x12\x10\n\x08response\x18\x06 \x01(\t\"\x10\n\x04Type\x12\x08\n\x04TEXT\x10\x00\x42\t\n\x07Promoteb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api.openai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPENAI._serialized_start=27
  _OPENAI._serialized_end=176
  _OPENAI_TYPE._serialized_start=149
  _OPENAI_TYPE._serialized_end=165
# @@protoc_insertion_point(module_scope)
